[package]
name = "backend"
version = "0.1.0"
edition = "2023_11"

[scripts]
test = "snforge test"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.18.0" }

[dev-dependencies]
cairo_test = "2.8.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.33.0" }

[[target.starknet-contract]]
sierra = true
